apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: aws-rds-reboot 
  version: 0.1.0
  annotations:
    categories: kube-aws
spec:
  displayName: aws-rds-reboot 
  categoryDescription: >
    it execs inside target pods to run the chaos inject commands, waits for the chaos duration and reverts the chaos 
  keywords: 
    - "aws" 
    - "rds" 
    - "kube-aws"
  platforms: 
    - "Minikube"
  maturity: alpha
  maintainers: 
    - name: ispeakc0de 
      email: shubham@chaosnative.com 
  minKubeVersion: 1.12.0 
  provider: 
    name: ChaosNative
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: latest
  links: 
    - name: Documentation 
      url: https://docs.litmuschaos.io/docs/getstarted/ 
  icon:
    - url: 
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/kube-aws/aws-rds-reboot/experiment.yaml
