apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: kubernetes-state-v0.1.0 
  annotations:
    categories: "Kubernetes"
    vendor: "CNCF"
    createdAt: 2019-08-12T10:28:08Z
    repository: https://github.com/litmuschaos/community-charts
    support: https://slack.kubernetes.io/
spec:
  displayName: state 
  description: >
    Contains chaos to disrupt state of kubernetes resources. 
    Examples include pod-delete, container-kill
  keywords:
    - Kubernetes
    - State 
  version: v0.1.0
  maturity: alpha
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Source Code
      url: https://github.com/kubernetes/kubernetes
  icon:
    - base64data: ""
      mediatype: ""
