---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: gcp-vm-disk-loss-by-label
  version: 0.1.0
  annotations:
    categories: GCP
    vendor: Harness

spec:
  displayName: GCP VM Disk Loss By Label
  categoryDescription: >
    Causes loss of a non-boot storage persistent disk from a GCP VM instance filtered by a label for a specified duration before attaching them back.
  keywords:
    - GCP
  platforms:
    - "Minikube"
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - url:
      mediatype: ""
