---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2022-07-27T10:28:08Z
  name: ec2-stop-by-tag
  version: 0.1.0
  annotations:
    categories: AWS
    vendor: Harness
spec:
  displayName: EC2 Stop By Tag
  categoryDescription: |
    This fault causes termination of an EC2 instance for a certain chaos duration.
    - Causes termination of an EC2 instance using instance tags before bringing it back to running state after the specified chaos duration.
    - It helps to check the performance of the application on the EC2 instance.
  keywords:
    - AWS
  platforms:
    - AWS
  chaosType: infra
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://docs.harness.io/category/kl0mxwpfw1-hce-category
  icon:
    - url:
      mediatype: ""
